baseURL                          = "http://example.com/"  # Your domain name. Must end with "/"
theme                            = "introduction"
DefaultContentLanguage           = "en"                    # Default language for multilingual sites
# disqusshortname                 = ""                       # https://gohugo.io/content-management/comments
# googleAnalytics                 = ""                       # https://gohugo.io/templates/internal/#google-analytics


[params]
    themeStyle                   = "dark"                 # Choose "light" or "dark"
    fadeIn                       = true                    # Turn on/off the fade-in effect
    fadeInIndex                  = true                   # Turn on/off the fade-in effect on the index page even if fade-in was otherwise turned off
    email                        = "youremail@email.com"   # E-mail address for contact section
    customCSS                    = ["custom.css"]


    # Configure the home page
    [params.home]
        introHeight              = "fullheight"            # Input either "medium" or "large" or "fullheight"
        showLatest               = false                    # Show latest blog post summary
        showAllPosts             = false                   # Set true to list all posts on home page, or set false to link to separate blog list page
        numberOfProjectsToShow   = 3                       # Maximum number of projects to show on home page. Unset or comment out to show all projects


[[menu.main]]
    name    = "Contact"
    url     = "/"
    weight  = 0
[[menu.main]]
    name    = "Projects"
    url     = "/"
    weight  = 0
[[menu.main]]
    name    = "Blog"
    url     = "/blog/"
    weight  = 1